### ISSUE TITLE
Avoid doubling of base R color names

### ISSUE THREAD

**Issue by hneth** [hneth/unikn#3]
When using `seecol()` to mix and extend color palettes, the names of base R colors are repeated (e.g., `"white"` becomes `"whitewhite"`).

**Comment by nigradwohl** [comment]
This was due to searching both the palettes and the usual colorspace defined by colors().  As the two overlap (and sometimes use different names for the same color) sometimes colors were named twice. 
Different names for the same color are now separated by a slash, duplicates are removed before naming.

**Comment by hneth** [comment]
Thanks for the fix --- and the "/" solution is really useful, as it's interesting when mixing and extending color palettes yields predefined **base** R colors.
